// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO Task(id,created_at,updated_at,order_id,name,data,status) VALUES(
      gen_random_uuid(),
      NOW(),
      NOW(),
      $1,
      $2,
      $3,
      $4
) RETURNING id, created_at, updated_at, order_id, name, data, status
`

type CreateTaskParams struct {
	OrderID uuid.UUID
	Name    string
	Data    string
	Status  string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.OrderID,
		arg.Name,
		arg.Data,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.Name,
		&i.Data,
		&i.Status,
	)
	return i, err
}
