// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_tasks.sql

package database

import (
	"context"
)

const deleteAllTasks = `-- name: DeleteAllTasks :exec
DELETE FROM Task
`

func (q *Queries) DeleteAllTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTasks)
	return err
}
