// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_task_by_month.sql

package database

import (
	"context"
	"time"
)

const getTaskByMonth = `-- name: GetTaskByMonth :many
SELECT id, created_at, updated_at, order_id, name, data, status FROM Task WHERE created_at >= date_trunc('month', $1::TIMESTAMP)
      AND created_at <  date_trunc('month', $1::TIMESTAMP) + INTERVAL '1 month'
`

func (q *Queries) GetTaskByMonth(ctx context.Context, dollar_1 time.Time) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskByMonth, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderID,
			&i.Name,
			&i.Data,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
