// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_task_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, order_id, name, data, status FROM Task WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.Name,
		&i.Data,
		&i.Status,
	)
	return i, err
}
