// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	OrderID   uuid.UUID
	Name      string
	Data      string
	Status    string
}
