// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_task_status.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE Task 
SET 
updated_at = NOW(),
status = $2
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
